# Data Extraction, Part II

In [179]:
import pandas as pd
import pickle
import datetime

import seaborn as sns
import matplotlib.pyplot as plt
import datetime

## 1. Hospitalizations by state

In [180]:
# Take a look at the format Austin put the data into:
cases = pickle.load(open("../data/us_state_cases_deaths.p", "rb"))
display(cases.sort_values(by=["date"], ascending=True))

           date           state  fips  cases  deaths abbrev
0    2020-01-21         Alabama     1      0       0     AL
318  2020-01-21        Arkansas     5      0       0     AR
3286 2020-01-21      New Jersey    34      0       0     NJ
5512 2020-01-21   West Virginia    54      0       0     WV
4770 2020-01-21       Tennessee    47      0       0     TN
...         ...             ...   ...    ...     ...    ...
4557 2020-05-05    Rhode Island    44   9933     355     RI
1165 2020-05-05         Georgia    13  28876    1277     GA
4663 2020-05-05  South Carolina    45   6841     296     SC
1907 2020-05-05          Kansas    20   5603     160     KS
5829 2020-05-05         Wyoming    56    452       7     WY

[5830 rows x 6 columns]

In [181]:
hospitalizations_df = pd.read_csv("../data/raw_data/covidtracking_historic_states_data_raw.csv")
"""
Sort the DF by state and date, so that for each state, we see the first date of recorded hospitalizations,
all the way down to the end.
"""
hospitalizations_df = hospitalizations_df.sort_values(by=["state", "date"], ascending=True, axis=0).reset_index(drop=True)

# Date is an integer here, and if you try to automatically use datetime on it, it assumes it's unix timestamp, 
# so we must manually convert: from a float like: 20200126

hospitalizations_df["date"] = hospitalizations_df["date"].apply(str)
hospitalizations_df["date"] = pd.to_datetime(hospitalizations_df["date"].apply(
    lambda x: datetime.datetime(day=int(x[6:8]), month=int(x[4:6]), year=int(x[0:4]))
))

hospitalizations_df["date"]
display(hospitalizations_df)

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,2020-03-06,AK,0.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,9,8,8,2,NaN,NaN,NaN,NaN,NaN
1,2020-03-07,AK,0.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,14,12,12,2,0.0,0.0,4.0,0.0,4.0
2,2020-03-08,AK,0.0,14.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,20,14,14,2,0.0,0.0,2.0,0.0,2.0
3,2020-03-09,AK,0.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,32,23,23,2,0.0,0.0,9.0,0.0,9.0
4,2020-03-10,AK,0.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,32,23,23,2,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3540,2020-05-03,WY,579.0,9640.0,NaN,13.0,60.0,NaN,NaN,NaN,...,60.0,10219,10219,10219,56,0.0,2.0,177.0,13.0,190.0
3541,2020-05-04,WY,586.0,9868.0,NaN,13.0,60.0,NaN,NaN,NaN,...,60.0,10454,10454,10454,56,0.0,0.0,228.0,7.0,235.0
3542,2020-05-05,WY,596.0,10319.0,NaN,13.0,60.0,NaN,NaN,NaN,...,60.0,10915,10915,10915,56,0.0,0.0,451.0,10.0,461.0
3543,2020-05-06,WY,604.0,11403.0,NaN,11.0,60.0,NaN,NaN,NaN,...,60.0,12007,12007,12007,56,0.0,0.0,1084.0,8.0,1092.0
3544,2020-05-07,WY,631.0,11403.0,NaN,11.0,59.0,NaN,NaN,NaN,...,59.0,12034,12034,12034,56,0.0,-1.0,0.0,27.0,27.0

In [182]:
"""
Let's see what the minimum date is for each state, though:
"""
display(hospitalizations_df.groupby(["state"]).agg({"date": "min"}))

            date
state
AK    2020-03-06
AL    2020-03-07
AR    2020-03-06
AS    2020-03-16
AZ    2020-03-04
CA    2020-03-04
CO    2020-03-05
CT    2020-03-07
DC    2020-03-05
DE    2020-03-06
FL    2020-03-04
GA    2020-03-04
GU    2020-03-16
HI    2020-03-07
IA    2020-03-06
ID    2020-03-07
IL    2020-03-04
IN    2020-03-06
KS    2020-03-06
KY    2020-03-06
LA    2020-03-07
MA    2020-03-12
MD    2020-03-05
ME    2020-03-07
MI    2020-03-01
MN    2020-03-06
MO    2020-03-07
MP    2020-03-16
MS    2020-03-07
MT    2020-03-07
NC    2020-03-04
ND    2020-03-07
NE    2020-03-05
NH    2020-03-04
NJ    2020-03-05
NM    2020-03-06
NV    2020-03-05
NY    2020-03-04
OH    2020-03-05
OK    2020-03-07
OR    2020-03-04
PA    2020-03-06
PR    2020-03-16
RI    2020-03-01
SC    2020-03-04
SD    2020-03-07
TN    2020-03-05
TX    2020-03-04
UT    2020-03-07
VA    2020-03-05
VI    2020-03-16
VT    2020-03-06
WA    2020-01-22
WI    2020-03-04
WV    2020-03-06
WY    2020-03-07

In [183]:
# map state abbreviation
states_to_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

"""
NOTE:  Austin's dataset came with state full name, 
but this one does the reverse, so let's flip this dict.
"""

abbrev_to_states = dict(map(reversed, states_to_abbrev.items()))
print(abbrev_to_states)

{'AL': 'Alabama', 'AK': 'Alaska', 'AS': 'American Samoa', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia', 'FL': 'Florida', 'GA': 'Georgia', 'GU': 'Guam', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'MP': 'Northern Mariana Islands', 'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania', 'PR': 'Puerto Rico', 'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VI': 'Virgin Islands', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming'}

In [184]:
# now match Austin's state formatting, where a column called "state" displays full state name
# and a column called "abbrev" displays the abbreviation
hospitalizations_df["abbrev"] = hospitalizations_df["state"]
hospitalizations_df["state"] = hospitalizations_df["state"].map(abbrev_to_states)

In [185]:
hospitalizations_df.columns

Index(['date', 'state', 'positive', 'negative', 'pending',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'recovered', 'dataQualityGrade', 'lastUpdateEt', 'hash', 'dateChecked',
       'death', 'hospitalized', 'total', 'totalTestResults', 'posNeg', 'fips',
       'deathIncrease', 'hospitalizedIncrease', 'negativeIncrease',
       'positiveIncrease', 'totalTestResultsIncrease', 'abbrev'],
      dtype='object')

In [187]:
"""
I mostly just want to get a sense of whether there are any missing dates in between the recorded days,
or if I just need to impute a bunch of dates to match up with the time frame that Austin set. 

His minimum date is: 2020-01-21

So, let's do some investigations. First, just look at a set from a specific date.
"""
pd.set_option("display.max_rows", 1000)
display(hospitalizations_df[hospitalizations_df["abbrev"] == "AK"])

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,abbrev
0,2020-03-06,Alaska,0.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,...,9,8,8,2,NaN,NaN,NaN,NaN,NaN,AK
1,2020-03-07,Alaska,0.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,...,14,12,12,2,0.0,0.0,4.0,0.0,4.0,AK
2,2020-03-08,Alaska,0.0,14.0,6.0,NaN,NaN,NaN,NaN,NaN,...,20,14,14,2,0.0,0.0,2.0,0.0,2.0,AK
3,2020-03-09,Alaska,0.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,...,32,23,23,2,0.0,0.0,9.0,0.0,9.0,AK
4,2020-03-10,Alaska,0.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,...,32,23,23,2,0.0,0.0,0.0,0.0,0.0,AK
5,2020-03-11,Alaska,0.0,46.0,14.0,NaN,NaN,NaN,NaN,NaN,...,60,46,46,2,0.0,0.0,23.0,0.0,23.0,AK
6,2020-03-12,Alaska,0.0,46.0,14.0,NaN,NaN,NaN,NaN,NaN,...,60,46,46,2,0.0,0.0,0.0,0.0,0.0,AK
7,2020-03-13,Alaska,1.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,...,60,60,60,2,0.0,0.0,13.0,1.0,14.0,AK
8,2020-03-14,Alaska,1.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,...,144,144,144,2,0.0,0.0,84.0,0.0,84.0,AK
9,2020-03-15,Alaska,1.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,...,144,144,144,2,0.0,0.0,0.0,0.0,0.0,AK
10,2020-03-16,Alaska,1.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN,...,144,144,144,2,0.0,0.0,0.0,0.0,0.0,AK
11,2020-03-17,Alaska,3.0,334.0,NaN,NaN,NaN,NaN,NaN,NaN,...,337,337,337,2,0.0,0.0,191.0,2.0,193.0,AK
12,2020-03-18,Alaska,6.0,406.0,NaN,NaN,NaN,NaN,NaN,NaN,...,412,412,412,2,0.0,0.0,72.0,3.0,75.0,AK
13,2020-03-19,Alaska,6.0,432.0,NaN,NaN,NaN,NaN,NaN,NaN,...,438,438,438,2,0.0,0.0,26.0,0.0,26.0,AK
14,2020-03-20,Alaska,12.0,686.0,NaN,NaN,NaN,NaN,NaN,NaN,...,698,698,698,2,0.0,0.0,254.0,6.0,260.0,AK
15,2020-03-21,Alaska,14.0,758.0,NaN,NaN,0.0,NaN,NaN,NaN,...,772,772,772,2,0.0,0.0,72.0,2.0,74.0,AK
16,2020-03-22,Alaska,22.0,946.0,NaN,NaN,0.0,NaN,NaN,NaN,...,968,968,968,2,0.0,0.0,188.0,8.0,196.0,AK
17,2020-03-23,Alaska,22.0,946.0,NaN,NaN,0.0,NaN,NaN,NaN,...,968,968,968,2,0.0,0.0,0.0,0.0,0.0,AK
18,2020-03-24,Alaska,36.0,986.0,NaN,NaN,0.0,NaN,NaN,NaN,...,1022,1022,1022,2,0.0,0.0,40.0,14.0,54.0,AK
19,2020-03-25,Alaska,42.0,1649.0,NaN,NaN,1.0,NaN,NaN,NaN,...,1691,1691,1691,2,1.0,1.0,663.0,6.0,669.0,AK
20,2020-03-26,Alaska,59.0,1801.0,NaN,NaN,3.0,NaN,NaN,NaN,...,1860,1860,1860,2,0.0,2.0,152.0,17.0,169.0,AK
21,2020-03-27,Alaska,69.0,2319.0,13.0,NaN,3.0,NaN,NaN,NaN,...,2401,2388,2388,2,0.0,0.0,518.0,10.0,528.0,AK
22,2020-03-28,Alaska,85.0,2836.0,NaN,NaN,5.0,NaN,NaN,NaN,...,2921,2921,2921,2,1.0,2.0,517.0,16.0,533.0,AK
23,2020-03-29,Alaska,102.0,3232.0,NaN,NaN,6.0,NaN,NaN,NaN,...,3334,3334,3334,2,0.0,1.0,396.0,17.0,413.0,AK
24,2020-03-30,Alaska,114.0,3540.0,NaN,NaN,7.0,NaN,NaN,NaN,...,3654,3654,3654,2,1.0,1.0,308.0,12.0,320.0,AK
25,2020-03-31,Alaska,119.0,3594.0,NaN,NaN,7.0,NaN,NaN,NaN,...,3713,3713,3713,2,0.0,0.0,54.0,5.0,59.0,AK
26,2020-04-01,Alaska,133.0,4470.0,NaN,NaN,9.0,NaN,NaN,NaN,...,4603,4603,4603,2,0.0,2.0,876.0,14.0,890.0,AK
27,2020-04-02,Alaska,143.0,4879.0,NaN,NaN,9.0,NaN,NaN,NaN,...,5022,5022,5022,2,0.0,0.0,409.0,10.0,419.0,AK
28,2020-04-03,Alaska,157.0,5859.0,NaN,NaN,15.0,NaN,NaN,NaN,...,6016,6016,6016,2,0.0,6.0,980.0,14.0,994.0,AK
29,2020-04-04,Alaska,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,...,6040,6040,6040,2,2.0,1.0,10.0,14.0,24.0,AK
30,2020-04-05,Alaska,185.0,6099.0,NaN,NaN,20.0,NaN,NaN,NaN,...,6284,6284,6284,2,1.0,4.0,230.0,14.0,244.0,AK
31,2020-04-06,Alaska,191.0,6692.0,NaN,NaN,23.0,NaN,NaN,NaN,...,6883,6883,6883,2,0.0,3.0,593.0,6.0,599.0,AK
32,2020-04-07,Alaska,213.0,6700.0,NaN,NaN,23.0,NaN,NaN,NaN,...,6913,6913,6913,2,0.0,0.0,8.0,22.0,30.0,AK
33,2020-04-08,Alaska,226.0,6842.0,NaN,NaN,27.0,NaN,NaN,NaN,...,7068,7068,7068,2,1.0,4.0,142.0,13.0,155.0,AK
34,2020-04-09,Alaska,235.0,6988.0,NaN,NaN,27.0,NaN,NaN,NaN,...,7223,7223,7223,2,0.0,0.0,146.0,9.0,155.0,AK
35,2020-04-10,Alaska,246.0,7186.0,NaN,NaN,28.0,NaN,NaN,NaN,...,7432,7432,7432,2,0.0,1.0,198.0,11.0,209.0,AK
36,2020-04-11,Alaska,257.0,7475.0,NaN,NaN,31.0,NaN,NaN,NaN,...,7732,7732,7732,2,1.0,3.0,289.0,11.0,300.0,AK
37,2020-04-12,Alaska,272.0,7766.0,NaN,NaN,31.0,NaN,NaN,NaN,...,8038,8038,8038,2,0.0,0.0,291.0,15.0,306.0,AK
38,2020-04-13,Alaska,277.0,7553.0,NaN,NaN,32.0,NaN,NaN,NaN,...,7830,7830,7830,2,0.0,1.0,-213.0,5.0,-208.0,AK
39,2020-04-14,Alaska,285.0,8063.0,NaN,NaN,32.0,NaN,NaN,NaN,...,8348,8348,8348,2,1.0,0.0,510.0,8.0,518.0,AK
40,2020-04-15,Alaska,293.0,8371.0,NaN,NaN,34.0,NaN,NaN,NaN,...,8664,8664,8664,2,0.0,2.0,308.0,8.0,316.0,AK
41,2020-04-16,Alaska,300.0,8435.0,NaN,NaN,35.0,NaN,NaN,NaN,...,8735,8735,8735,2,0.0,1.0,64.0,7.0,71.0,AK
42,2020-04-17,Alaska,309.0,9141.0,NaN,NaN,36.0,NaN,NaN,NaN,...,9450,9450,9450,2,0.0,1.0,706.0,9.0,715.0,AK
43,2020-04-18,Alaska,314.0,9341.0,NaN,39.0,36.0,NaN,NaN,NaN,...,9655,9655,9655,2,0.0,0.0,200.0,5.0,205.0,AK
44,2020-04-19,Alaska,319.0,9576.0,NaN,37.0,36.0,NaN,NaN,NaN,...,9895,9895,9895,2,0.0,0.0,235.0,5.0,240.0,AK
45,2020-04-20,Alaska,321.0,9803.0,NaN,46.0,36.0,NaN,NaN,NaN,...,10124,10124,10124,2,0.0,0.0,227.0,2.0,229.0,AK
46,2020-04-21,Alaska,329.0,10790.0,NaN,42.0,36.0,NaN,NaN,NaN,...,11119,11119,11119,2,0.0,0.0,987.0,8.0,995.0,AK
47,2020-04-22,Alaska,335.0,11824.0,NaN,39.0,36.0,NaN,NaN,NaN,...,12159,12159,12159,2,0.0,0.0,1034.0,6.0,1040.0,AK
48,2020-04-23,Alaska,337.0,11824.0,NaN,42.0,NaN,NaN,NaN,NaN,...,12161,12161,12161,2,0.0,0.0,0.0,2.0,2.0,AK
49,2020-04-24,Alaska,339.0,11942.0,NaN,36.0,NaN,NaN,NaN,NaN,...,12281,12281,12281,2,0.0,0.0,118.0,2.0,120.0,AK
50,2020-04-25,Alaska,339.0,15393.0,NaN,32.0,NaN,NaN,NaN,NaN,...,15732,15732,15732,2,0.0,0.0,3451.0,0.0,3451.0,AK
51,2020-04-26,Alaska,341.0,15836.0,NaN,14.0,NaN,NaN,NaN,NaN,...,16177,16177,16177,2,0.0,0.0,443.0,2.0,445.0,AK
52,2020-04-27,Alaska,345.0,15911.0,NaN,10.0,NaN,NaN,NaN,NaN,...,16256,16256,16256,2,0.0,0.0,75.0,4.0,79.0,AK
53,2020-04-28,Alaska,351.0,16738.0,NaN,16.0,NaN,NaN,NaN,NaN,...,17089,17089,17089,2,0.0,0.0,827.0,6.0,833.0,AK
54,2020-04-29,Alaska,355.0,18764.0,NaN,14.0,NaN,NaN,NaN,NaN,...,19119,19119,19119,2,0.0,0.0,2026.0,4.0,2030.0,AK
55,2020-04-30,Alaska,355.0,18764.0,NaN,19.0,NaN,NaN,NaN,NaN,...,19119,19119,19119,2,0.0,0.0,0.0,0.0,0.0,AK
56,2020-05-01,Alaska,364.0,19961.0,NaN,25.0,NaN,NaN,NaN,NaN,...,20325,20325,20325,2,0.0,0.0,1197.0,9.0,1206.0,AK
57,2020-05-02,Alaska,365.0,21034.0,NaN,10.0,NaN,NaN,NaN,NaN,...,21399,21399,21399,2,0.0,0.0,1073.0,1.0,1074.0,AK
58,2020-05-03,Alaska,368.0,21210.0,NaN,12.0,NaN,NaN,NaN,NaN,...,21578,21578,21578,2,0.0,0.0,176.0,3.0,179.0,AK
59,2020-05-04,Alaska,370.0,21353.0,NaN,12.0,NaN,NaN,NaN,NaN,...,21723,21723,21723,2,0.0,0.0,143.0,2.0,145.0,AK
60,2020-05-05,Alaska,371.0,22321.0,NaN,13.0,NaN,NaN,NaN,NaN,...,22692,22692,22692,2,0.0,0.0,968.0,1.0,969.0,AK
61,2020-05-06,Alaska,372.0,23283.0,NaN,8.0,NaN,NaN,NaN,NaN,...,23655,23655,23655,2,1.0,0.0,962.0,1.0,963.0,AK
62,2020-05-07,Alaska,374.0,23967.0,NaN,12.0,NaN,NaN,NaN,NaN,...,24341,24341,24341,2,0.0,0.0,684.0,2.0,686.0,AK

In [189]:
"""
Now, let's just quickly check all of them.

(I wish I hadn't named my df such a long name).
"""
for state in states_to_abbrev.keys():
    # Get minimum and maximum date per state.
    min_date = hospitalizations_df[hospitalizations_df["state"] == state]["date"].min()
    max_date = hospitalizations_df[hospitalizations_df["state"] == state]["date"].max()

    missing_dates_per_state = pd.date_range(start=min_date, end=max_date).difference(
        hospitalizations_df[hospitalizations_df["state"] == state]["date"].values
    )
    print(missing_dates_per_state)

DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
DatetimeIndex([], dtype='datetime64[ns]', freq=None)

In [200]:
hospitalizations_df.columns

Index(['date', 'state', 'positive', 'negative', 'pending',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'recovered', 'dataQualityGrade', 'lastUpdateEt', 'hash', 'dateChecked',
       'death', 'hospitalized', 'total', 'totalTestResults', 'posNeg', 'fips',
       'deathIncrease', 'hospitalizedIncrease', 'negativeIncrease',
       'positiveIncrease', 'totalTestResultsIncrease', 'abbrev'],
      dtype='object')

In [270]:
MIN_DATE = datetime.datetime(year=2020, month=1, day=21)
MAX_DATE = datetime.datetime(year=2020, month=5, day=5)

def impute_missing_dates(df):
    """
    Function that imputes hospitalization data for missing 
    dates with None. This is to keep consistent with the original dataset,
    where they indicate none for unknown values.
    
    This is augmented from Austin's extractions notebook.
    
    
    NOTE: that there are lots of fields where there are missing values because of the discrepancy
    in terms of whether states are reporting the data or not. Imputing 0 is misleading here, since this
    is  possibly just unreported data. Because of this, I only added zeros if there are 
    numeric values in the column for a given state. 
    
    Otherwise, leave NaN / None in order to indicate that the state has not started collecting data.
    """

    # iterate through all states
    imputed_data = []
    for state in df["state"].unique():
        # build list of missing dates
        # https://stackoverflow.com/questions/7274267/print-all-day-dates-between-two-dates
        sdate = MIN_DATE
        edate = df.loc[df["state"] == state]["date"].min()
        delta = edate - sdate 

        # Iterate through all missing dates and impute hospitalization status data
        # To keep fidelity with the dataset, instead of imputing 0s, we'll impute None
        for i in range(delta.days):
            day = sdate + datetime.timedelta(days=i)
            imputed_data.append({"date": day,
                                 "state": state,
                                 "positive": None,
                                 "negative": None,
                                 "pending": None,
                                 "hospitalizedCurrently": None,
                                 "hospitalizedCumulative": None,
                                 "inIcuCurrently": None,
                                 "inIcuCumulative": None,
                                 "onVentilatorCurrently": None,
                                 "onVentilatorCumulative": None,
                                 "recovered": None,
                                 "dataQualityGrade": None,
                                 "lastUpdateEt": None,
                                 "hash": None,
                                 "dateChecked": None,
                                 "death": None,
                                 "hospitalized": None, 
                                 "total": None, 
                                 "pending": None,
                                 "totalTestResults": None,
                                 "posNeg": None,
                                 "fips": None,
                                 "deathIncrease": None,
                                 "hospitalizedIncrease": None,
                                 "negativeIncrease": None,
                                 "positiveIncrease": None,
                                 "totalTestResultsIncrease": None,
                                 "abbrev": states_to_abbrev[state]})   
       

    # final cleanup
    new_df = pd.concat([pd.DataFrame(imputed_data), df])
    new_df = new_df.sort_values(by=["state", "date"]).reset_index().drop("index", axis=1)
    
    return new_df

In [271]:
imputed_hosp_df = impute_missing_dates(hospitalizations_df)
display(imputed_hosp_df)

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,abbrev
0,2020-01-21,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AL
1,2020-01-22,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AL
2,2020-01-23,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AL
3,2020-01-24,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AL
4,2020-01-25,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6043,2020-05-03,Wyoming,579.0,9640.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10219,10219,10219,56,0.0,2.0,177.0,13.0,190.0,WY
6044,2020-05-04,Wyoming,586.0,9868.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10454,10454,10454,56,0.0,0.0,228.0,7.0,235.0,WY
6045,2020-05-05,Wyoming,596.0,10319.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10915,10915,10915,56,0.0,0.0,451.0,10.0,461.0,WY
6046,2020-05-06,Wyoming,604.0,11403.0,NaN,11.0,60.0,NaN,NaN,NaN,...,12007,12007,12007,56,0.0,0.0,1084.0,8.0,1092.0,WY
6047,2020-05-07,Wyoming,631.0,11403.0,NaN,11.0,59.0,NaN,NaN,NaN,...,12034,12034,12034,56,0.0,-1.0,0.0,27.0,27.0,WY

In [277]:
numeric_columns = ['positive', 'negative', 'pending',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'recovered', 'death', 'hospitalized', 'total', 
        'totalTestResults', 'posNeg', 'fips',
       'deathIncrease', 'hospitalizedIncrease', 'negativeIncrease',
       'positiveIncrease', 'totalTestResultsIncrease']


def fill_nulls_until_first_val(df):
    """
    One issue with this dataset is that they have a bunch of missing values.
    However, some states don't even report some of the metrics. Because of this, 
    we need to be careful not to impute with 0s where the dataset is simply missing.
    
    So, we'll only impute zeros for any column for a given state that has started 
    recording values. Since sometimes the states skip recording the data on some days 
    (found a couple instances of this), we must also only do this for NaNS / Nones 
    leading up to the first recorded value.
    """
    df = df.copy()
    for state in states_to_abbrev.keys():
        state_df = df[df["state"] == state]
        for nc in numeric_columns:
            # Returns a series; indices are not kept, so don't use this again.
            state_rows_nc = df[df["state"] == state][nc]
            if state_rows_nc.isnull().values.all():
                # Don't impute; this state doesn't actually record this metric
                continue;
            """
            Only fill up to the first recording of this metric:
            """
            first_recorded_value = state_df[state_df[nc].notnull() == True]["date"].idxmin()
            start_state_nc = state_df[state_df[nc].notnull() == False]["date"].idxmin()
            df[nc][start_state_nc:first_recorded_value] = 0
    return df
            

imputed_hosp = fill_nulls_until_first_val(imputed_hosp_df)

/Users/Emily/opt/anaconda3/envs/cs109b/lib/python3.7/site-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [278]:
pd.set_option("display.max_rows", 1000)
display(imputed_hosp)

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,abbrev
0,2020-01-21,Alabama,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,AL
1,2020-01-22,Alabama,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,AL
2,2020-01-23,Alabama,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,AL
3,2020-01-24,Alabama,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,AL
4,2020-01-25,Alabama,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6043,2020-05-03,Wyoming,579.0,9640.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10219,10219,10219,56,0.0,2.0,177.0,13.0,190.0,WY
6044,2020-05-04,Wyoming,586.0,9868.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10454,10454,10454,56,0.0,0.0,228.0,7.0,235.0,WY
6045,2020-05-05,Wyoming,596.0,10319.0,NaN,13.0,60.0,NaN,NaN,NaN,...,10915,10915,10915,56,0.0,0.0,451.0,10.0,461.0,WY
6046,2020-05-06,Wyoming,604.0,11403.0,NaN,11.0,60.0,NaN,NaN,NaN,...,12007,12007,12007,56,0.0,0.0,1084.0,8.0,1092.0,WY
6047,2020-05-07,Wyoming,631.0,11403.0,NaN,11.0,59.0,NaN,NaN,NaN,...,12034,12034,12034,56,0.0,-1.0,0.0,27.0,27.0,WY

In [78]:
# dump to pickle file
pickle.dump(imputed_hosp, open("../data/covidtracking_historic_states_data.p", "wb" ))